#!/bin/bash
#
#
# script de instalación
# wget https://raw.githubusercontent.com/uGeek/blog/master/scripts/ohmyzsh ; bash  ohmyzsh ; rm ohmyzsh
#  
# https://ugeek.github.io
#
#

# Instalando  ZSH y git-core
sudo apt install zsh git-core

# Descargando Oh My ZSH y ejecutarlo
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh

# Cambiar la shell a ZSH
chsh -s `which zsh`

# Instalando las Fuentes Powerline para ZSH
sudo apt install fonts-powerline

# Clonar el repositorio

git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

#Añadir en el archivo de configuración

echo "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh" >>  ~/.zshrc

#Reiniciamos nuestra terminal y ya podemos disfrutar del nuevo plugin

# Fuentes
#- https://ohmyz.sh/
#- http://zshwiki.org/
#- https://github.com/zsh-users/zsh-autosuggestions
